name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@38e2fb5cb2754159cc40b39c2baf72c6eb4e0042 # 2.0.5
        env:
          JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
